import "@ui5/webcomponents-icons/dist/AllIcons.js"
import '@ui5/webcomponents-icons/dist/Assets.js'

import "@ui5/webcomponents/dist/Assets.js"
import "@ui5/webcomponents/dist/Badge.js"
import "@ui5/webcomponents/dist/BusyIndicator.js"
import "@ui5/webcomponents/dist/Button.js"
import "@ui5/webcomponents/dist/Card.js"
import "@ui5/webcomponents/dist/CardHeader.js"
import "@ui5/webcomponents/dist/CheckBox.js"
import "@ui5/webcomponents/dist/Dialog.js"
import "@ui5/webcomponents/dist/DatePicker.js"
import "@ui5/webcomponents/dist/DateRangePicker.js"
import "@ui5/webcomponents/dist/DateTimePicker.js"
import "@ui5/webcomponents/dist/Icon.js"
import "@ui5/webcomponents/dist/Input.js"
import "@ui5/webcomponents/dist/features/InputSuggestions.js"
import "@ui5/webcomponents/dist/features/InputElementsFormSupport.js"
import "@ui5/webcomponents/dist/Label.js"
import "@ui5/webcomponents/dist/MessageStrip.js"
import "@ui5/webcomponents/dist/MultiComboBox.js"
import "@ui5/webcomponents/dist/MultiComboBoxItem.js"
import "@ui5/webcomponents/dist/Option.js"
import "@ui5/webcomponents/dist/Panel.js"
import "@ui5/webcomponents/dist/Popover.js"
import "@ui5/webcomponents/dist/RadioButton.js"
import "@ui5/webcomponents/dist/Select.js"
import "@ui5/webcomponents/dist/StepInput.js"
import "@ui5/webcomponents/dist/Switch.js"
import "@ui5/webcomponents/dist/Table.js"
import "@ui5/webcomponents/dist/TabContainer.js"
import "@ui5/webcomponents/dist/Tab.js"
import "@ui5/webcomponents/dist/TableColumn.js"
import "@ui5/webcomponents/dist/TableRow.js"
import "@ui5/webcomponents/dist/TableCell.js"
import "@ui5/webcomponents/dist/TextArea.js"

import "@ui5/webcomponents-fiori/dist/Assets.js"
import "@ui5/webcomponents-fiori/dist/Bar.js"
import "@ui5/webcomponents-fiori/dist/ShellBar.js"
import "@ui5/webcomponents-fiori/dist/SideNavigation.js"
import "@ui5/webcomponents-fiori/dist/SideNavigationItem.js"
import "@ui5/webcomponents-fiori/dist/SideNavigationSubItem.js"
import "@ui5/webcomponents-fiori/dist/ViewSettingsDialog.js"
import {setLanguage} from '@ui5/webcomponents-base/dist/config/Language'

setLanguage('ru')