# Generated by Django 4.2.7 on 2024-01-18 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_alter_events_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventEmails',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('event_published', models.BooleanField(default=False, verbose_name='Сообщение об опубликованном мероприятии')),
                ('event_start_tomorrow', models.BooleanField(default=False, verbose_name='Сообщение о начала мероприятия (завтра)')),
                ('event_start', models.BooleanField(default=False, verbose_name='Сообщение о начала мероприятия (сегодня)')),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Запись с проверкой почты по мероприятиям',
                'verbose_name_plural': 'Записи с проверкой почты по мероприятиям',
            },
        ),
    ]
