# Generated by Django 4.1.3 on 2023-12-06 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('event_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время фиксации события')),
                ('source', models.CharField(max_length=300, verbose_name='Источник события')),
                ('rec_type', models.CharField(choices=[('Личный кабинет администратора', 'Личный кабинет администратора'), ('Работа с заявками на мероприятия', 'Работа с заявками на мероприятия'), ('Авторизация/Регистрация', 'Авторизация/Регистрация'), ('Работа с очередью задач Celery', 'Работа с очередью задач Celery'), ('Работа с мероприятиями', 'Работа с мероприятиями'), ('Работа с отчетами', 'Работа с отчетами'), ('Личный кабинет пользователей', 'Личный кабинет пользователей')], max_length=500, verbose_name='Тип события')),
                ('description', models.TextField(max_length=4000, verbose_name='Детали события')),
            ],
            options={
                'verbose_name': 'Запись журнала событий',
                'verbose_name_plural': 'Записи журнала событий',
            },
        ),
    ]
