# Generated by Django 4.1.3 on 2023-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_event_result_alter_journal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rec_type',
            field=models.CharField(choices=[('DEFAULT', 'Не определено'), ('ADMINS', 'Личный кабинет администратора'), ('APPLICATIONS', 'Работа с заявками на мероприятия'), ('AUTHEN', 'Авторизация/Регистрация'), ('STATES', 'Работа с государствами'), ('PROFILE', 'Работа с профилем пользователя'), ('CELERY_APP', 'Работа с очередью задач Celery'), ('EVENTS', 'Работа с мероприятиями'), ('JOURNALS', 'Работа с журналами'), ('REPORTS', 'Работа с отчетами'), ('USERS', 'Личный кабинет пользователей')], max_length=50, verbose_name='Тип события'),
        ),
    ]
