FROM node:21-alpine

WORKDIR /front

RUN rm -rf /node_modules

RUN rm -rf package-lock.json

ENV PATH /front/node_modules/.bin:$PATH

ARG VITE_BACKEND_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

COPY package.json /front/package.json

RUN npm install --silent

COPY . /front

CMD npm run build
