# Generated by Django 4.1.3 on 2023-12-06 03:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(default='Новое государство', max_length=200, unique=True, verbose_name='Наименование государства')),
            ],
            options={
                'verbose_name': 'Государство',
                'verbose_name_plural': 'Государства',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(14)], verbose_name='Возраст')),
                ('sex', models.BooleanField(default=False, verbose_name='Пол')),
                ('phone', models.CharField(max_length=18, unique=True, verbose_name='Номер телефона')),
                ('oo_fullname', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Полное наименование образовательной организации')),
                ('oo_shortname', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Краткое наименование образовательной организации')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
                ('state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authen.states', verbose_name='Государство')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
