# Generated by Django 4.1.3 on 2023-12-11 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(default='Имя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.CharField(default='+7 (999) 999-99-99', max_length=18, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='surname',
            field=models.CharField(default='Фамилия', max_length=150, verbose_name='Фамилия'),
        ),
    ]
