# Generated by Django 4.1.3 on 2023-12-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_profiles_age_alter_profiles_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
