# Generated by Django 4.1.3 on 2023-12-06 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventForms',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование формы проведения мероприятия')),
            ],
            options={
                'verbose_name': 'Форма проведения',
                'verbose_name_plural': 'Формы проведения',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование типа мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='ParticipantCategories',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование категории участников')),
            ],
            options={
                'verbose_name': 'Категория участников',
                'verbose_name_plural': 'Категории участников',
            },
        ),
    ]
